spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
server:
  port: 8082
authentication:
  admin:
    username: admin
    password: admin
  user:
    username: user
    password: user
  jwt:
    key: key